output_dir: '/home/yuwei/experiment/cvpr/uhd4k_ll_pretrain'
data:
  train_dir: /home/data/yuwei/data/uhd4k_ll/train
  test_dir: /home/data/yuwei/data/uhd4k_ll/test

model:
  in_channel: 3
  model_channel: 8

train_loader:
  num_workers: 8
  batch_size: 2
  loader: resize
  img_size: (1024, 1024)
  shuffle: True

test_loader:
  num_workers: 8
  batch_size: 1
  loader: default
  img_size: (1200, 1600)
  shuffle: False
  gt_size: (2160, 3840)

optimizer:
  type: step
  total_epoch: 100
  lr: 0.001
  T_0: 100
  T_MULT: 1
  ETA_MIN: 0.000001
  step: 20
  gamma: 0.75

hyper_params:
  x_lambda: 0.03

resume:
  flag: False
  checkpoint: Null

evaluate_intervel: 5
